import { link } from '../../../../config'
import { BasePage } from '../../Objects/base_page'
import { CheckBox } from '../../Objects/Elements/check_box'
describe('Test Check box', () => {
  beforeEach(() => {
    cy.visit('/')
    const basePage = new BasePage()
    basePage.goToSectionFromCategoryCards('Elements')
    basePage.goToSectionFromleftPanel('Check Box')
  })

  it('Should click expand and click each button', () => {
    const checkBox = new CheckBox()
    checkBox.showAllButtons()
    checkBox.clickSingleButton()

    cy.contains('Home')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Desktop')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Notes')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Commands')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Documents')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('WorkSpace')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Office')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Downloads')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Word File')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
    cy.contains('Excel File')
      .parent()
      .find('.rct-checkbox')
      .children()
      .should('have.class', 'rct-icon rct-icon-check')
  })
})
